backend:
  name: github
  repo: Veduy/Veduy.github.io
  branch: main # 또는 사용 중인 기본 브랜치 이름

media_folder: "images" # 이미지가 저장될 경로
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
